# Generated by Django 5.0.6 on 2026-08-07 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='professional_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='standard_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
